# Generated by Django 3.1.6 on 2021-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoIlicito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('quantidade', models.IntegerField()),
                ('porcao', models.SmallIntegerField(choices=[(1, '5 gramas'), (2, '10 gramas'), (3, '15 gramas'), (4, '25 gramas'), (5, '50 gramas')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
